condominios:
  - id: 1
    CONDOMINIO_ID: 27
    RAZAO_SOCIAL: "CONDOMINIO EDIFÍCIO ANTARES"
    CNPJ: ""
  
  - id: 2
    CONDOMINIO_ID: 4
    RAZAO_SOCIAL: "CONDOMÍNIO RESIDENCIAL ANDALUCIA"
    CNPJ: ""
  
  - id: 3
    CONDOMINIO_ID: 1819
    RAZAO_SOCIAL: "CONDOMÍNIO RESIDENCIAL ATENAS"
    CNPJ: ""
  
  - id 4:
    CONDOMINIO_ID: 1603
    RAZAO_SOCIAL: "CONDOMÍNIO RESIDENCIAL ITAMBÉ"
    CNPJ: ""
  
  - id: 5
    CONDOMINIO_ID: 1556
    RAZAO_SOCIAL: "CONDOMÍNIO RESIDENCIAL PEDRA BONITA"
    CNPJ: ""
  
  - id: 6
    CONDOMINIO_ID: 112
    RAZAO_SOCIAL: "CONDOMÍNIO RESIDENCIAL SÃO CONRADO"
    CNPJ: ""

  - id: 7
    CONDOMINIO_ID: 577
    RAZAO_SOCIAL: "CONDOMÍNIO RESIDENCIAL SITIOCAS I"
    CNPJ: ""
  
  - id: 8
    CONDOMINIO_ID: 205
    RAZAO_SOCIAL: "CONDOMÍNIO RESIDENCIAL VILLAS DE GALICIA II"
    CNPJ: ""
  
  - id: 9
    CONDOMINIO_ID: 1167
    RAZAO_SOCIAL: "CONDOMÍNIO ROSSI IDEAL PARQUE DOS JATOBAS I"
    CNPJ: ""
  
  - id: 10
    CONDOMINIO_ID: 68
    RAZAO_SOCIAL: "CONDOMÍNIO VILLAGIO BANDEIRA 2"
    CNPJ: ""
  
  - id: 11
    CONDOMINIO_ID: 89
    RAZAO_SOCIAL: "CONDOMÍNIO VILLAGIO BANDEIRA 3"
    CNPJ: ""
  
  - id: 12
    CONDOMINIO_ID: 789
    RAZAO_SOCIAL: "CONDOMÍNIO VILLAS DE CASTILLA I"
    CNPJ: ""

  - id: 13
    CONDOMINIO_ID: 164
    RAZAO_SOCIAL: "RESIDENCIAL RITA VIEIRA PARQUE"
    CNPJ: ""
